# Generated by Django 5.0.2 on 2024-02-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="stuff",
            field=models.CharField(default=None, max_length=255, verbose_name="Stuff"),
        ),
    ]
