# Generated by Django 5.0.2 on 2024-02-21 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_users_stuff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="stuff",
        ),
    ]
