# Generated by Django 5.0.2 on 2024-02-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_users_stuff"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="usr_type",
            field=models.CharField(
                blank=True,
                choices=[("Admin", "Admin"), ("Company", "Company")],
                max_length=7,
                null=True,
            ),
        ),
    ]
