# Generated by Django 5.0.2 on 2024-02-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_users_usr_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="usr_type",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Company", "Company")],
                max_length=7,
                null=True,
            ),
        ),
    ]
