# Generated by Django 5.0.2 on 2024-02-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_users_usr_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="company_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="users",
            name="pswd",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
