# Generated by Django 5.0.2 on 2024-02-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_users_company_id_users_pswd"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.CharField(max_length=255)),
            ],
        ),
    ]
