# Generated by Django 5.0.2 on 2024-02-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_company_total_resources"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Resource_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_name", models.CharField(max_length=255)),
                ("resource_desc", models.TextField()),
                ("resource_type", models.CharField(max_length=255)),
            ],
        ),
    ]
