# Generated by Django 5.0.2 on 2024-02-23 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_resource_resource_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="users",
            table="Users",
        ),
    ]
