# Generated by Django 5.0.2 on 2024-02-23 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_users_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="company",
            table="Company",
        ),
        migrations.AlterModelTable(
            name="resource",
            table="Resource",
        ),
        migrations.AlterModelTable(
            name="resource_type",
            table="Resource Type",
        ),
    ]
