# Generated by Django 5.0.2 on 2024-02-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usr", models.CharField(max_length=255)),
                (
                    "usr_type",
                    models.CharField(
                        choices=[("Admin", "Admin"), ("Company", "Company")],
                        max_length=7,
                        null=True,
                    ),
                ),
                ("pswd", models.CharField(max_length=255, null=True)),
                ("company_id", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
