# Generated by Django 5.0.2 on 2024-02-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_users_options_alter_users_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="usr",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
