# Generated by Django 5.0.2 on 2024-02-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "usr_type",
                    models.CharField(
                        choices=[("Admin", "Admin"), ("Company", "Company")],
                        max_length=7,
                        null=True,
                    ),
                ),
                ("password", models.CharField(max_length=255, null=True)),
                ("company_id", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "custom_users",
            },
        ),
    ]
