# Generated by Django 5.0.2 on 2024-03-10 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "usr_type",
                    models.CharField(
                        choices=[("Admin", "Admin"), ("Company", "Company")],
                        max_length=7,
                        null=True,
                    ),
                ),
                ("password", models.CharField(max_length=255, null=True)),
                ("company_id", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "custom_users",
            },
        ),
        migrations.CreateModel(
            name="Resource_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_type_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("booking_status", models.BooleanField(default=True)),
                (
                    "available_date",
                    models.DateField(blank=True, default="2024-03-10", null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_app.resource_info",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_date",
                    models.DateField(blank=True, default="2024-03-10", null=True),
                ),
                (
                    "booking_date",
                    models.DateField(blank=True, default="2024-03-10", null=True),
                ),
                ("current_status", models.BooleanField(default=True)),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_app.resource",
                    ),
                ),
            ],
        ),
    ]
