# Generated by Django 5.0.2 on 2024-03-19 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "usr_type",
                    models.CharField(
                        choices=[("Company", "Company"), ("Admin", "Admin")],
                        default="Company",
                        max_length=7,
                        null=True,
                    ),
                ),
                ("password", models.CharField(max_length=255, null=True)),
                ("company_id", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "custom_users",
            },
        ),
        migrations.CreateModel(
            name="Resource_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_type_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("booking_status", models.BooleanField(default=True)),
                ("available_date", models.DateField(default="2024-03-19", null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_app.resource_info",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("res_type", models.CharField(blank=True, max_length=255)),
                (
                    "available_date",
                    models.DateField(blank=True, default="2024-03-19", null=True),
                ),
                (
                    "booking_date",
                    models.DateField(blank=True, default="2024-03-19", null=True),
                ),
                (
                    "current_status",
                    models.BooleanField(
                        choices=[(1, "booked"), (0, "released")], default=True
                    ),
                ),
                ("owner", models.CharField(blank=True, max_length=255)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_app.resource",
                    ),
                ),
            ],
        ),
    ]
