# Generated by Django 5.0.2 on 2024-03-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="release_date",
            field=models.DateField(blank=True, default="2024-03-10", null=True),
        ),
    ]
