# Generated by Django 5.0.2 on 2024-03-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0002_booking_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="available_date",
            field=models.DateField(blank=True, default="2024-03-11", null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(blank=True, default="2024-03-11", null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="release_date",
            field=models.DateField(blank=True, default="2024-03-11", null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="available_date",
            field=models.DateField(blank=True, default="2024-03-11", null=True),
        ),
    ]
