# Generated by Django 5.0.2 on 2024-03-08 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0003_resource_created_by_delete_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_app.resource",
                    ),
                ),
            ],
        ),
    ]
