# Generated by Django 5.0.2 on 2024-03-11 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0004_booking_res_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="res_id",
        ),
    ]
