# Generated by Django 5.0.2 on 2024-03-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0004_resource_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource_info",
            name="resource_type_name",
        ),
        migrations.AddField(
            model_name="resource_info",
            name="resource_type_name_id",
            field=models.CharField(default="def", max_length=255),
            preserve_default=False,
        ),
    ]
