# Generated by Django 5.0.2 on 2024-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0005_remove_booking_res_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="owner",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
