# Generated by Django 5.0.2 on 2024-03-08 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0005_remove_resource_info_resource_type_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource_info",
            old_name="resource_type_name_id",
            new_name="resource_type_name",
        ),
    ]
