# Generated by Django 5.0.2 on 2024-03-08 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "base_app",
            "0006_rename_resource_type_name_id_resource_info_resource_type_name",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base_app.resource_info"
            ),
        ),
    ]
