# Generated by Django 5.0.2 on 2024-03-08 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0007_alter_resource_resource_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="resource_type",
            new_name="resource_type_id",
        ),
    ]
