# Generated by Django 5.0.2 on 2024-03-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0008_booking_res_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="current_status",
            field=models.BooleanField(
                choices=[(1, "booked"), (0, "released")], default=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
