# Generated by Django 5.0.2 on 2024-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0009_alter_booking_current_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="available_date",
            field=models.DateField(default="2024-03-12", null=True),
        ),
    ]
