# Generated by Django 5.0.2 on 2024-03-12 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0010_alter_resource_available_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="base_app.resource",
            ),
        ),
    ]
