# Generated by Django 5.0.2 on 2024-03-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0012_alter_booking_available_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="owner",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
